### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by haesleinhuepf** [ajinkya-kulkarni/PyTextureAnalysis#1]
Hi @ajinkya-kulkarni ,

again, great to see this repository out. I'd have a small proposal: Would you mind adding a license file? Without one, people cannot reuse your code as you don't grant them any right to copy (copyright). 

When choosing a license, I generally recommend using one that is compatible with other libraries in the same ecosystem and checking the copyright of libraries your library depends on. See also: choosealicense.com

Thanks!

Best,
Robert

**Comment by ajinkya-kulkarni** [comment]
I just added the license file; hope it solves the issue. Thanks for the suggestion!

**Comment by haesleinhuepf** [comment]
Awesome thanks!
