### ISSUE TITLE
Documentation on definitions

### ISSUE THREAD

**Issue by ogencoglu** [ajinkya-kulkarni/PyTextureAnalysis#5]
Thanks for the work!

Is there a documentation on what does coherence, local orientation, local density etc. mean in this context?

**Comment by ajinkya-kulkarni** [comment]
Hi, here are the commonly used terms when it comes to texture analysis of fibrous structure.

Coherence:
Coherence refers to the uniformity or regularity of a pattern. In the context of collagen fibers, coherence can provide information about the density, alignment, and regularity of the fibers in a given area. When collagen fibers are highly coherent, they tend to be densely packed and exhibit uniformity in their distribution. On the other hand, low coherence might suggest irregular or sparse distribution, which could be indicative of pathological conditions or alterations in tissue remodeling.

Orientation:
Orientation pertains to the direction or angle at which the fibers are aligned in relation to a reference axis. The orientation of collagen fibers can provide insights into the structural organization and the mechanical properties of the tissue. In many tissues, collagen fibers are oriented in specific directions to provide strength and flexibility based on the functional requirements. For instance, in tendons, which need to withstand tension in a specific direction, collagen fibers are typically aligned in parallel with the direction of tension.
